### ISSUE TITLE
불편합니다.

### ISSUE THREAD

**Issue by takhyun12** [jyoonab/STUDY_CS_Basics#1]
폴더명이 `1.Memory_control` 인게 불편합니다.

`1.` 뒤에 한칸 띄워쓰기 해주세요.

`2.`는 띄워쓰기가 되어있는데, 왜 1은 안해두셧죠?

불편합니다.

**Comment by jyoonab** [comment]
이름 정하는데 실수가 있었고 말씀하신대로 변경해 놨습니다.
지적 감사합니다~
